services:
  - type: web
    name: nauticalflow-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true